spring:
  application:
    name: book-store-online-be
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book-store-database
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: tlcnwithtothimynhan

default:
  password: 12345678
  avatar: null
  updatingInfoBook: "Đang cập nhập"

paging:
  default:
    page: 0
    size: 20

google:
  verifyUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=

logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/book-store-online-be.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7

server:
  port: 8080